### PR TITLE
Made things work

### PR DESCRIPTION
**Pull request by eburdon**

### CODE REVIEW

**Comment by jordan-heemskerk** [comment]
Wow awesome work!

**Comment by eburdon** [comment]
Usage note: I removed the MapReduce package from this PR since we should already have it in our workspaces. This makes it somewhat incomplete... if another user tries to run just this, they'll run into missing package errors. Later TODO task?

Also might run into missing packages for the github ones... just need to run a `go get`

**Comment by eburdon** [comment]
And thanks! :D

**Comment by jordan-heemskerk** [comment]
Oh. I guess we should have another repo with the generic map reduce package?
Then people will be able to: go get <github URL> 
Otherwise just add a copy to this.
Total TODO when its not 12am :P
On May 13, 2016 12:15 AM, EBurdon notifications@github.com wrote:Usage note: I removed the MapReduce package from this PR since we should already have it in our workspaces. This makes it somewhat incomplete... if another user tries to run just this, they'll run into missing package errors. Later TODO task?

**Pull request merged**
