### PR TITLE
Splitting

### PR DESCRIPTION
**Pull request by jordan-heemskerk**

### CODE REVIEW

**Comment by eburdon** [comment]
Oh were you waiting on me to merge?? My bad - is it ready to go?

**Comment by jordan-heemskerk** [comment]
No its not ready to go... :( 
I don't know if I can get it done for Thursday, feel free to take over if you feel like it

**Comment by eburdon** [comment]
I should have some free time this weekend (before all the other projects start) - what was the other half of this idea? If I know the expected output from your parser, I could get started on the mapreduce with fakes.

**Comment by jordan-heemskerk** [comment]
I didn't fully have what the output should exactly be yet, so that's free to be designed. What you has been done is the ability to provide a custom split function in the framework (it was hardcoded before) and then some quick goquery (like jQuery) magic to find all the HTML elements that specify friends. Feel free to make some executive decisions on what the output should actually be! I will have some time to address this on the weekend as well.

**Comment by jordan-heemskerk** [comment]
Given the new strategy, this update is stale :(

**Pull request closed without merging**
